version: 2.1

aliases:
  - &workspace
    at: ~/
  - &deps-cache
    keys:
      - v1-deps-{{ .Branch }}-{{ checksum "package-lock.lock" }}

node-env: &node-env
  working_directory: ~/
  docker:
    - image: cimg/node:15.10.0

jobs:
  setup:
    <<: *node-env
    steps:
      - checkout
      - restore_cache: *deps-cache
      - run:
          name: Checking environment
          command: node --version
      - run:
          name: Installing dependencies
          command: npm ci
      - save_cache:
          name: Caching dependencies
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.lock" }}
          paths:
            - .cache
      - persist_to_workspace:
          root: ~/
          paths: 
            - .cache

  test-unit:
    <<: *node-env
    steps:
      - attach_workspace: *workspace
      - restore_cache: *deps-cache
      - run:
          name: Running unit tests
          command: npm test:ci
